DROP TABLE datafinaldepurado;
CREATE TABLE datafinaldepurado (
estu_tipodocumento TEXT,
estu_nacionalidad TEXT,
estu_genero TEXT,
estu_fechanacimiento TIMESTAMP, --TEXT, 
periodo INTEGER, 
estu_consecutivo TEXT,
estu_estudiante TEXT,
estu_depto_reside TEXT,
estu_cod_reside_depto TEXT, --INTEGER
estu_mcpio_reside TEXT,
estu_cod_reside_mcpio TEXT, --INTEGER,
estu_cole_termino TEXT, 
estu_valormatriculauniversidad TEXT,
estu_pagomatriculabeca TEXT,
estu_pagomatriculacredito TEXT,
estu_pagomatriculapadres TEXT,
estu_pagomatriculapropio TEXT, 
estu_simulacrotipoicfes TEXT,
estu_actividadrefuerzoareas TEXT, 
estu_actividadrefuerzogeneric TEXT,
estu_tipodocumentosb11 TEXT,
fami_educacionpadre TEXT,
fami_educacionmadre TEXT,
fami_estratovivienda TEXT,
fami_tieneinternet TEXT,
fami_tienecomputador TEXT,
fami_tienelavadora TEXT,
fami_tieneautomovil TEXT,
estu_horassemanatrabaja TEXT,
inst_cod_institucion FLOAT, --INTEGER
inst_nombre_institucion TEXT,
estu_prgm_academico TEXT,
--estu_snies_prgmacademico TEXT, --INTEGER 
estu_prgm_codmunicipio INTEGER, 
estu_prgm_municipio TEXT,
estu_prgm_departamento TEXT,
estu_nivel_prgm_academico TEXT,
estu_metodo_prgm TEXT,
estu_nucleo_pregrado TEXT,
estu_inst_codmunicipio FLOAT, --INTEGER
estu_inst_municipio TEXT,
estu_inst_departamento TEXT,
inst_caracter_academico TEXT,
inst_origen TEXT,
estu_cod_mcpio_presentacion INTEGER, 
estu_mcpio_presentacion TEXT,
estu_depto_presentacion TEXT,
estu_cod_depto_presentacion INTEGER, 
mod_razona_cuantitat_punt FLOAT, --INTEGER
mod_razona_cuantitativo_pnal FLOAT, 
mod_lectura_critica_punt FLOAT, --INTEGER, 
mod_lectura_critica_pnal FLOAT, 
mod_competen_ciudada_punt FLOAT, --INTEGER, 
mod_competen_ciudada_pnal FLOAT, 
mod_ingles_punt FLOAT, --INTEGER, 
mod_ingles_desem TEXT,
mod_ingles_pnal FLOAT, 
mod_comuni_escrita_punt FLOAT, --INTEGER, 
mod_comuni_escrita_desem INTEGER, 
mod_comuni_escrita_pnal FLOAT, 
estu_estadoinvestigacion TEXT, 
periodox TEXT,
prueba TEXT,
tipo_prueba TEXT
);
